config/routes.rb
Rails.application.routes.draw do

  resources :prisons, only: :show do
    resources :inmates, only: [:new, :create]
  end


  resources :inmates, only: :destroy do
    resources :inmate_crimes, only: [:new, :create]
  end
end


# InmateCrime.new
# crime:
# inmate:

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crime.rb
class Crime < ApplicationRecord
  has_many :inmate_crimes
  has_many :inmates, through: :inmate_crimes
  validates :name, presence: true

  def to_label
    name.humanize
  end
end

app/models/inmate.rb
class Inmate < ApplicationRecord
  belongs_to :prison
  has_many :inmate_crimes
  has_many :crimes, through: :inmate_crimes
  validates :name, presence: true
  # validates :crime, inclusion: { in: CRIMES }
end

app/models/inmate_crime.rb
class InmateCrime < ApplicationRecord
  belongs_to :crime
  belongs_to :inmate
  validates_uniqueness_of :crime_id, scope: :inmate_id
end

app/models/prison.rb
class Prison < ApplicationRecord
  has_many :inmates, dependent: :destroy
  validates :name, presence: true
  validates :banner_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inmate_crimes_controller.rb
class InmateCrimesController < ApplicationController
  def new
    @inmate = Inmate.find(params[:inmate_id])
    @inmate_crime = InmateCrime.new
  end

  def create
    @inmate = Inmate.find(params[:inmate_id])
    @inmate_crime = InmateCrime.new
    if params[:inmate_crime]
      Crime.where(id: params[:inmate_crime][:crime_id]).each do |crime|
        @inmate_crime = InmateCrime.new(crime: crime)
        @inmate_crime.inmate = @inmate
        @inmate_crime.save
      end
    end
    if @inmate_crime.valid?
      redirect_to prison_path(@inmate.prison)
    else
      render :new
    end
  end

  private

  def inmate_crime_params
    params.require(:inmate_crime).permit(:crime_id)
  end
end

app/controllers/inmates_controller.rb
class InmatesController < ApplicationController
  before_action :set_prison, only: [:new, :create]

  def new
    @inmate = Inmate.new
  end

  def create
    @inmate = Inmate.new(inmate_params)
    @inmate.prison = @prison
    if @inmate.save
      redirect_to prison_path(@prison)
    else
      render :new
    end
  end

  def destroy
    @inmate = Inmate.find(params[:id])
    @inmate.destroy
    redirect_to prison_path(@inmate.prison)
  end

  private

  def inmate_params
    params.require(:inmate).permit(:name, :image_url, :crime, :death_row)
  end

  def set_prison
    @prison = Prison.find(params[:prison_id])
  end
end

app/controllers/prisons_controller.rb
class PrisonsController < ApplicationController
  before_action :set_prison, only: [:show, :edit, :update, :destroy]

  # GET /prisons
  def index
    @prisons = Prison.all
  end

  # GET /prisons/1
  def show
  end

  # GET /prisons/new
  def new
    @prison = Prison.new
  end

  # GET /prisons/1/edit
  def edit
  end

  # POST /prisons
  def create
    @prison = Prison.new(prison_params)

    if @prison.save
      redirect_to @prison, notice: 'Prison was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /prisons/1
  def update
    if @prison.update(prison_params)
      redirect_to @prison, notice: 'Prison was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /prisons/1
  def destroy
    @prison.destroy
    redirect_to prisons_url, notice: 'Prison was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prison
      @prison = Prison.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def prison_params
      params.require(:prison).permit(:name, :banner_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inmate_crimes_helper.rb
module InmateCrimesHelper
end

app/helpers/inmates_helper.rb
module InmatesHelper
end

app/helpers/prisons_helper.rb
module PrisonsHelper
end

app/views/inmate_crimes/new.html.erb
<div class="container">
  <div class="row justify-content-center m-5">
    <div class="col-12 col-sm-8">
      <h1>Add crime for <%= @inmate.name %></h1>
      <%= simple_form_for [@inmate, @inmate_crime] do |f| %>
        <%= f.association :crime, input_html: {multiple: true }, include_hidden: false %>
        <%= f.button :submit, "Assign Crime", class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>
<form action=""></form>

app/views/inmates/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 mt-3">
      <%= simple_form_for [@prison, @inmate] do |f| %>
        <%= f.input :name, placeholder: "Sulav" %>
        <%= f.input :image_url, placeholder: "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/dluzi5onoqlnu3cjgyky.jpg" %>
        <%= f.input :crime, collection: Inmate::CRIMES %>
        <%= f.input :death_row %>
        <%= f.submit "Incarcerate", class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaxSecurity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/prisons/_form.html.erb
<%= simple_form_for(@prison) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/prisons/edit.html.erb
<h1>Editing Prison</h1>

<%= render 'form', prison: @prison %>

<%= link_to 'Show', @prison %> |
<%= link_to 'Back', prisons_path %>

app/views/prisons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prisons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prisons.each do |prison| %>
      <tr>
        <td><%= prison.name %></td>
        <td><%= prison.banner_url %></td>
        <td><%= link_to 'Show', prison %></td>
        <td><%= link_to 'Edit', edit_prison_path(prison) %></td>
        <td><%= link_to 'Destroy', prison, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prison', new_prison_path %>

app/views/prisons/new.html.erb
<h1>New Prison</h1>

<%= render 'form', prison: @prison %>

<%= link_to 'Back', prisons_path %>

app/views/prisons/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @prison.banner_url %>);">
  <div class="container">
    <h1>Welcome to <strong><%= @prison.name %></strong></h1>
    <%= link_to "Join Now", new_prison_inmate_path(@prison), class: "btn btn-danger" %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12 card-grid m-3">
      <% @prison.inmates.each do |inmate| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= inmate.image_url %>)">
          <%= link_to "+", new_inmate_inmate_crime_path(inmate), class: "btn btn-default card-add-crime"  %>
          <div class="card-tags">
            <% inmate.crimes.each do |crime| %>
              <span><%= crime.name %></span>
            <% end %>
          </div>
          <%= inmate.name %>
          <% if inmate.death_row %>
            <%= link_to "+", inmate_path(inmate), method: :delete, class: "card-remove-link", data: { confirm: "Excute #{inmate.name}?"} %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>